### PR TITLE
Add workflow to regenerate and upload crypt archive

### PR DESCRIPTION
**Pull request by fcooper8472**
Work in progress!

### CODE REVIEW

**Comment by mirams** [comment]
You are a really useful engine Fergus (I have been watching Thomas the Tank Engine)

**Comment by fcooper8472** [comment]
> You are a really useful engine Fergus (I have been watching Thomas the Tank Engine)

:steam_locomotive:

**Comment by fcooper8472** [comment]
I'm being very naughty and merging this without review as the workflow (with a workflow dispatch trigger) needs to exist on the default branch in order to check that it works.

**Comment by jmosborne** [comment]
If this is doing what I think its doing you're my new favourite person!

**Pull request merged**
