### PR TITLE
Issue 100

### PR DESCRIPTION
**Pull request by jmpf**
Fixes issue #100 on machine with /tmp and /home on different SSDs.
Should be ready to go.

### CODE REVIEW

**Comment by fcooper8472** [comment]
There's a compile failure with the classic intel compiler. But the warnings it's emitting have prompted me to open #116 (and PR #117).

I think removing intel classic is the right move at this juncture, and will have the added benefit of fixing this specific build error.

**Review by fcooper8472 — APPROVED** [review]
Content looks good - happy for this to be merged as soon as the CI is green.

**Comment by jmpf** [comment]
Slightly different behaviour has altered coverage.  Investigating.

**Comment by jmpf** [comment]
Note that ddb0ecb removes corner case code for creating a directory with a trailing slash.  Without this the old code would fall over like this:
`***** TestArchivingHelperClasses.hpp *****


Entering TestArchiveLocationInfoMethods
Passed
Entering TestArchiveLocationInfoProcessUniqueNaming
Passed
Entering TestProcessSpecificArchive
Passed
Entering TestArchiveOpenerReadAndWrite

Chaste termination: /home/jmpf/Workspace/Chaste/global/src/OutputFileHandler.cpp:231: Error making test output folder: boost::filesystem::create_directory: Permission denied: "/tmp/jmpf/testoutput/archiving_helpers/."`

The std::filesystem doesn't need this

**Pull request merged**
