### PR TITLE
HDF5 1.12 support

### LINKED ISSUE #163: HDF5 1.12 support
This issue continues the discussion for legacy trac ticket 3063

---
@mirams created the following ticket on 2021-04-20 at 14:31:40, it is owned by @mirams
 
A major release that might have some substantial changes to address:
https://portal.hdfgroup.org/display/HDF5/Migrating+from+HDF5+1.10+to+HDF5+1.12

* **status:** new
* **type:** user story
* **priority:** normal
* **component:** heart
* **milestone:** Iteration 33
* **effort:** 16
* **effortexpended:** 0
* **initialeffort:** 16

---
Comment by @jmpf on 2022-07-06 at 15:13:21

When working on #37 I used the migration advice to make a hack to use old API. This may work.  Quick addition to `io/src/common/AbstractHdf5Access.hpp`:

```
+#define H5_USE_110_API
 #include <hdf5.h>
 #include <string>
```

### PR DESCRIPTION
**Pull request by kwabenantim**
**Summary**
* Supports #163

### CODE REVIEW

**Review by jmpf — APPROVED** [review]
This looks good.  I was tempted to only set the #define if the version of HDF5 was >= 1.12 but, of course, previous version of HDF5 simply ignore the #define.  Perhaps there should be a comment:
// Set backward compatibility for HDF5 1.12 or above before including hdf5.h header file

**Comment by kwabenantim** [comment]
Thanks @jmpf. I'll add the comment and install HDF5 1.12.2 in the [portability-06](https://github.com/Chaste#portability-testing) image.

**Comment by kwabenantim** [comment]
**Local Testing**
- [x] HDF5 1.12.0 build
- [x] HDF5 1.12.1 build
- [x] HDF5 1.12.0 Continuous
- [x] HDF5 1.12.1 Continuous
- [x] HDF5 1.12.0 Nightly
- [x] HDF5 1.12.1 Nightly

**Comment by kwabenantim** [comment]
**To Do**
- [x] Pull in `TestDiskSpace` fix  from: #169 
- [x] Remove temporary `portability-dev` test: [ac1c2745](https://github.com/Chaste/Chaste/pull/167/commits/ac1c274521352c3fd468f6919b5b634f1647cb00)
- [x] Push `portability-06` with HDF5 1.12.2 to DockerHub: https://github.com/Chaste/dependency-modules/pull/58
- [x] Update [dependency wiki](https://github.com/Chaste/dependency-modules/wiki/HDF5).

**Pull request merged**
