### PR TITLE
Support Ubuntu 24.10 Oracular

### LINKED ISSUE #339: Support Ubuntu 24.10 Oracular
## Dependencies
```xml
     <Compiler>
             <NameAndVersion>/usr/bin/c++, version 14.2.0</NameAndVersion>
             <Flags>-Wall -Werror -Wnon-virtual-dtor -Woverloaded-virtual -Wextra -Wno-attributes -Wno-unused-parameter -Wvla -Wimplicit-fallthrough=2 -g</Flags>
     </Compiler>
     <Libraries>
             <CompiledIn>
                     <PETSc>3.20.6</PETSc>
                     <Boost>1.83.0</Boost>
                     <HDF5>1.10.10</HDF5>
                     <Parmetis>4.0.3</Parmetis>
             </CompiledIn>
             <Binaries>
                     <XSD>4.0.0</XSD>
             </Binaries>
             <Optional>
                     <SUNDIALS>6.4.1</SUNDIALS>
                     <VTK>9.3</VTK>
                     <Xerces>3.2.4</Xerces>
             </Optional>
     </Libraries>
     <ChasteCodegenVersion>chaste_codegen 0.10.5</ChasteCodegenVersion>
```

## Test failures out of the box

```
The following tests FAILED:
          3 - TestCitations (Failed)
         56 - TestChebyshevIteration (Failed)
         58 - TestLinearSystem (Failed)
        428 - TestMonodomainWithTimeAdaptivity (Failed)
```

- [ ] Minor update required to the PETSc citation
- [ ] Some genuine differences in LinAlg tests - need to investigate

### PR DESCRIPTION
**Pull request by fcooper8472**

### CODE REVIEW

**Comment by fcooper8472** [comment]
@jmpf the two remaining failing tests after these changes are:

The following tests FAILED:
         56 - TestChebyshevIteration (Failed)
        428 - TestMonodomainWithTimeAdaptivity (Failed)

The first one:

```
Entering TestChebyshevAdaptiveVsNoAdaptive

/home/fcooper/GitRepos/Chaste/linalg/test/TestChebyshevIteration.hpp:169: Error: Expected (ls.mEigMin == 0.0124) up to 1e-4 (0.0001), found (0.0141 != 0.0124)
/home/fcooper/GitRepos/Chaste/linalg/test/TestChebyshevIteration.hpp:170: Error: Expected (ls.mEigMax == 1.8810) up to 1e-4 (0.0001), found (1.8876 != 1.8810)
/home/fcooper/GitRepos/Chaste/linalg/test/TestChebyshevIteration.hpp:201: Error: Expected (ls.mEigMin == 0.0124) up to 1e-4 (0.0001), found (0.0141 != 0.0124)
/home/fcooper/GitRepos/Chaste/linalg/test/TestChebyshevIteration.hpp:202: Error: Expected (ls.mEigMax == 1.8841) up to 1e-4 (0.0001), found (1.8878 != 1.8841)
Failed
```

The second one:

```
Entering TestWithChebyshevAndFixedIterations
428:          InMesh             Init           AssSys              Ode            Comms           AssRhs           NeuBCs           DirBCs              Ksp           Output   DataConversion         PostProc            User1            User2            User3            Total  
428:    0.700 (  7%)     0.039 (  0%)     4.627 ( 49%)     3.047 ( 32%)     0.037 (  0%)     0.092 (  1%)     0.001 (  0%)     0.000 (  0%)     0.284 (  3%)     0.024 (  0%)     0.000 (  0%)     0.000 (  0%)     0.000 (  0%)     0.000 (  0%)     0.000 (  0%)     9.489 (100%)  (seconds) 
428: 
428: /home/fcooper/GitRepos/Chaste/heart/test/monodomain/TestMonodomainWithTimeAdaptivity.hpp:183: Error: Expected (max_non_adaptive == 28.8346) up to 1e-3 (0.0010), found (28.8335 != 28.8346)
428:          InMesh             Init           AssSys              Ode            Comms           AssRhs           NeuBCs           DirBCs              Ksp           Output   DataConversion         PostProc            User1            User2            User3            Total  
428:    0.169 (  4%)     0.006 (  0%)     2.771 ( 68%)     0.919 ( 23%)     0.011 (  0%)     0.023 (  1%)     0.000 (  0%)     0.000 (  0%)     0.049 (  1%)     0.004 (  0%)     0.000 (  0%)     0.000 (  0%)     0.000 (  0%)     0.000 (  0%)     0.000 (  0%)     4.069 (100%)  (seconds) 
428: /home/fcooper/GitRepos/Chaste/heart/test/monodomain/TestMonodomainWithTimeAdaptivity.hpp:210: Error: Expected (max_adaptive == 25.6082) up to 1.25e-3 (0.0012), found (25.6102 != 25.6081)
428: Failed
```

Both relate to Chebyshev/KSP and we appear to have changes in numerical output. There's nothing obvious in the PETSc 3.20 release notes (https://petsc.org/release/changes/320/) but there are a number of KSP-related changes mentioned.

**Comment by fcooper8472** [comment]
@jmpf I have relaxed some thresholds so that the tests pass, but please let me know if you think a more thorough dive into these changes is warranted.

**Comment by jmpf** [comment]
> @jmpf I have relaxed some thresholds so that the tests pass, but please let me know if you think a more thorough dive into these changes is warranted.

Some of these are big (1e-4 to 1e-2 relative error) but probably OK. I don't think we know better.

**Review by kwabenantim — APPROVED** [review]
The CMake and portability workflow changes all look sensible to me.

**Pull request merged**
