### PR TITLE
Ignore ublas deprecation warnings in targeted way

### LINKED ISSUE #293: Intel builds failing due to deprecation warnings from boost
See e.g. here:
https://github.com/Chaste/Chaste/actions/runs/9758344511/job/26932687398

```
/usr/include/boost/numeric/ublas/detail/iterator.hpp:149:21: error: 'iterator<boost::numeric::ublas::sparse_bidirectional_iterator_tag, double>' is deprecated [-Werror,-Wdeprecated-declarations]
  149 |         public std::iterator<IC, T> {
      |                     ^
```

### PR DESCRIPTION
**Pull request by fcooper8472**
See #293

### CODE REVIEW

**Comment by fcooper8472** [comment]
@jmpf does this approach look OK to you? (assuming this or something like it works)

**Comment by mirams** [comment]
still seems to break but apart from that it looks great :-D

**Review by jmpf — COMMENTED** [review]
This approach looks good to me.

**Comment by fcooper8472** [comment]
> still seems to break but apart from that it looks great :-D

Yes, there's more deprecation problems in Boost! I'm going to switch to a slightly more general solution...

**Review by mirams — APPROVED** [review]

**Pull request merged**
