### PR TITLE
Modify portabilities for new Ubuntus

### LINKED ISSUE #197: Create GitHub runner docker images for newer Ubuntus
**Summary**
Create  images with dependency versions for:
* ~~[Ubuntu 22.10](https://packages.ubuntu.com/kinetic/) Kinetic Kudu~~ [End of Life](https://fridge.ubuntu.com/2023/06/14/ubuntu-22-10-kinetic-kudu-reaches-end-of-life-on-july-20-2023/)
* [Ubuntu 23.04](https://packages.ubuntu.com/lunar/)  Lunar Lobster
* [Ubuntu 23.10](https://packages.ubuntu.com/mantic/) Mantic Minotaur

**Tasks**
- [x] ~~Build docker image for `chaste/runner:kinetic.portability-dev`.~~
- [x] Build docker image for `chaste/runner:lunar.portability-dev`.
- [x] Build docker image for `chaste/runner:mantic.portability-dev`.
- [x] Modify boost modulefiles in old portability images to set `FindBoost.cmake` variables. 
- [x] Fix workflows to use `FindBoost.cmake` variables from modulefiles. 
- [x] Write developer documentation on building and testing new dependency versions (https://github.com/Chaste/developer_wiki/wiki/Portability-Testing)
- [x] Fix `cvector` errors.

**PRs**
* #205 
* https://github.com/Chaste/dependency-modules/pull/60
* https://github.com/Chaste/dependency-modules/pull/61
* https://github.com/Chaste/dependency-modules/pull/62
* https://github.com/Chaste/dependency-modules/pull/63

**Related Issues**
* #198

### LINKED ISSUE #231: Ignore some specific -Wmaybe-uninitialized c_vector warnings
For years now, every new version of GCC has been even more picky with thinking certain c_vector instances may be uninitialized.

Some of these warnings have been correct, but increasingly large numbers appear to be spurious.
Examples can be found on #205 (related to issue #197).

Following discussion, we have decided that as part of the BBSRC Milestone 2.2, we will investigate migrating from Boost uBLAS to Eigen.
As an interim measure, where appropriate, we will selectively ignore the warnings where they are judged to be spurious.

I intend to achieve this by creating a new header with some macros that will resolve to something like:

```cpp
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmaybe-uninitialized"

// Code that triggers the warning

#pragma GCC diagnostic pop
```

The header will ensure that these macros are only defined for GCC, so some empty macros will be created for other compilers.

This is a highly targeted way of ensuring that only very specific lines of code have the diagnostic ignored, and I propose only using this approach judiciously on a case-by-case basis where we have carefully examined the code emitting the warning.

### PR DESCRIPTION
**Pull request by kwabenantim**
**Related Issue**
* #197

### CODE REVIEW

**Comment by fcooper8472** [comment]
Following our discussion this morning, I have opened #231 which outlines a strategy for temporarily ignoring (in a very selective and targeted way) some -Wmaybe-uninitialized c_vector warnings.

The discussion indicated a preference to temporarily ignore the warnings, with a view to migrating from Boost uBLAS to Eigen in due course, as part of Milestone 2.2.

**Comment by fcooper8472** [comment]
I'm stuck on something that appears to be a genuine compiler warning; perhaps something for @jmpf or @mirams:

The following line calls `ComputeLinearInUCoeffInSourceTerm` with a second parameter as `nullptr`.

https://github.com/Chaste/Chaste/blob/7bf9a4d8803637cc055d4182e754777ffc75f189/pde/src/problem/AbstractLinearEllipticPde.hpp#L147

In `AbstractLinearEllipticPde`, the function `ComputeLinearInUCoeffInSourceTerm` is pure virtual, but one place it's defined is in:

https://github.com/Chaste/Chaste/blob/7bf9a4d8803637cc055d4182e754777ffc75f189/cell_based/src/cell_based_pde/pdes/AveragedSourceEllipticPde.cpp#L113-L118

What should this specialisation do in the case that the element is null?

**Comment by jmpf** [comment]
> What should this specialisation do in the case that the element is null?

What happens if we assert that it's not null? Does any test-suite fall over?

**Comment by fcooper8472** [comment]
@jmpf happy with the testing?

**Comment by jmpf** [comment]
> @jmpf happy with the testing?

d18f283 Yes.  The documentation is good too -- should hopefully make sense to future generations.

**Comment by fcooper8472** [comment]
@kwabenantim I sort of took over this PR! But I think with my latest commit, the portabilities now all pass, but this should also close all issues related to Ubuntu 24.04 support.

@mirams or @jmpf when reviewing this, it's currently expected that the project workflow fails, and the compiler failures for clang 16/17/18 and gcc 14 are expected to fail, but will be addressed by #322 .

**Review by mirams — APPROVED** [review]

**Pull request merged**
